<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Ppjub;
use Carbon\Carbon;

class PpjubSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $sampleData = [
            [
                'nama' => 'Ahmad bin Ali',
                'no_ic' => '891230-13-1581',
                'telefon' => '012-3456789',
                'email' => 'ahmad.ali@email.com',
                'alamat' => 'No. 123, Jalan Merdeka, Taman Damai, 96000 Sibu, Sarawak',
                'status' => 'Aktif',
                'tarikh_keahlian' => '2020-01-15',
                'created_by' => 1,
            ],
            [
                'nama' => 'Siti binti Mohamed',
                'no_ic' => '850722-02-5678',
                'telefon' => '013-4567890',
                'email' => 'siti.mohamed@email.com',
                'alamat' => 'No. 456, Jalan Utama, Taman Sentosa, 96000 Sibu, Sarawak',
                'status' => 'Aktif',
                'tarikh_keahlian' => '2019-06-20',
                'created_by' => 1,
            ],
            [
                'nama' => 'Ismail bin Hassan',
                'no_ic' => '881108-03-9012',
                'telefon' => '014-5678901',
                'email' => 'ismail.hassan@email.com',
                'alamat' => 'No. 789, Jalan Besar, Taman Indah, 96000 Sibu, Sarawak',
                'status' => 'Aktif',
                'tarikh_keahlian' => '2021-03-10',
                'created_by' => 1,
            ],
            [
                'nama' => 'Fatimah binti Omar',
                'no_ic' => '870914-04-3456',
                'telefon' => '015-6789012',
                'email' => 'fatimah.omar@email.com',
                'alamat' => 'No. 321, Jalan Baru, Taman Maju, 96000 Sibu, Sarawak',
                'status' => 'Tidak Aktif',
                'tarikh_keahlian' => '2018-12-05',
                'created_by' => 1,
            ],
            [
                'nama' => 'Abdullah bin Yusuf',
                'no_ic' => '861203-05-7890',
                'telefon' => '016-7890123',
                'email' => 'abdullah.yusuf@email.com',
                'alamat' => 'No. 654, Jalan Lama, Taman Harmoni, 96000 Sibu, Sarawak',
                'status' => 'Aktif',
                'tarikh_keahlian' => '2022-08-15',
                'created_by' => 1,
            ],
            [
                'nama' => 'Mohd Zulkifli bin Ahmad',
                'no_ic' => '900315-06-1234',
                'telefon' => '017-8901234',
                'email' => 'zulkifli.ahmad@email.com',
                'alamat' => 'No. 111, Jalan Ceria, Taman Bahagia, 96000 Sibu, Sarawak',
                'status' => 'Aktif',
                'tarikh_keahlian' => '2023-01-10',
                'created_by' => 1,
            ],
            [
                'nama' => 'Nor Azizah binti Ibrahim',
                'no_ic' => '920428-07-5678',
                'telefon' => '018-9012345',
                'email' => 'azizah.ibrahim@email.com',
                'alamat' => 'No. 222, Jalan Damai, Taman Sejahtera, 96000 Sibu, Sarawak',
                'status' => 'Aktif',
                'tarikh_keahlian' => '2023-03-15',
                'created_by' => 1,
            ],
            [
                'nama' => 'Khairul Anuar bin Mohd',
                'no_ic' => '880625-08-9012',
                'telefon' => '019-0123456',
                'email' => 'khairul.anuar@email.com',
                'alamat' => 'No. 333, Jalan Makmur, Taman Jaya, 96000 Sibu, Sarawak',
                'status' => 'Tidak Aktif',
                'tarikh_keahlian' => '2021-07-20',
                'created_by' => 1,
            ],
            [
                'nama' => 'Rohana binti Sulaiman',
                'no_ic' => '910812-09-3456',
                'telefon' => '011-1234567',
                'email' => 'rohana.sulaiman@email.com',
                'alamat' => 'No. 444, Jalan Maju, Taman Berjaya, 96000 Sibu, Sarawak',
                'status' => 'Aktif',
                'tarikh_keahlian' => '2022-11-25',
                'created_by' => 1,
            ],
            [
                'nama' => 'Azman bin Rosli',
                'no_ic' => '870319-10-7890',
                'telefon' => '012-2345678',
                'email' => 'azman.rosli@email.com',
                'alamat' => 'No. 555, Jalan Sukses, Taman Makmur, 96000 Sibu, Sarawak',
                'status' => 'Aktif',
                'tarikh_keahlian' => '2020-09-30',
                'created_by' => 1,
            ],
            [
                'nama' => 'Nurul Ain binti Kamal',
                'no_ic' => '930521-11-1234',
                'telefon' => '013-3456789',
                'email' => 'nurul.ain@email.com',
                'alamat' => 'No. 666, Jalan Cemerlang, Taman Gemilang, 96000 Sibu, Sarawak',
                'status' => 'Aktif',
                'tarikh_keahlian' => '2023-05-12',
                'created_by' => 1,
            ],
            [
                'nama' => 'Hisham bin Zainal',
                'no_ic' => '890704-12-5678',
                'telefon' => '014-4567890',
                'email' => 'hisham.zainal@email.com',
                'alamat' => 'No. 777, Jalan Berkat, Taman Rahmat, 96000 Sibu, Sarawak',
                'status' => 'Aktif',
                'tarikh_keahlian' => '2021-12-08',
                'created_by' => 1,
            ],
            [
                'nama' => 'Salmah binti Hashim',
                'no_ic' => '910926-13-9012',
                'telefon' => '015-5678901',
                'email' => 'salmah.hashim@email.com',
                'alamat' => 'No. 888, Jalan Mulia, Taman Indah, 96000 Sibu, Sarawak',
                'status' => 'Tidak Aktif',
                'tarikh_keahlian' => '2022-02-14',
                'created_by' => 1,
            ],
            [
                'nama' => 'Razali bin Omar',
                'no_ic' => '881215-14-3456',
                'telefon' => '016-6789012',
                'email' => 'razali.omar@email.com',
                'alamat' => 'No. 999, Jalan Utama, Taman Sentosa, 96000 Sibu, Sarawak',
                'status' => 'Aktif',
                'tarikh_keahlian' => '2020-06-18',
                'created_by' => 1,
            ],
            [
                'nama' => 'Zarina binti Yusof',
                'no_ic' => '920308-15-7890',
                'telefon' => '017-7890123',
                'email' => 'zarina.yusof@email.com',
                'alamat' => 'No. 1000, Jalan Besar, Taman Damai, 96000 Sibu, Sarawak',
                'status' => 'Aktif',
                'tarikh_keahlian' => '2023-08-22',
                'created_by' => 1,
            ],
            [
                'nama' => 'Mohd Faizal bin Ismail',
                'no_ic' => '891112-16-1234',
                'telefon' => '018-8901234',
                'email' => 'faizal.ismail@email.com',
                'alamat' => 'No. 1111, Jalan Merdeka, Taman Jaya, 96000 Sibu, Sarawak',
                'status' => 'Aktif',
                'tarikh_keahlian' => '2022-04-10',
                'created_by' => 1,
            ],
            [
                'nama' => 'Noraini binti Ahmad',
                'no_ic' => '900625-17-5678',
                'telefon' => '019-9012345',
                'email' => 'noraini.ahmad@email.com',
                'alamat' => 'No. 1112, Jalan Utama, Taman Sentosa, 96000 Sibu, Sarawak',
                'status' => 'Aktif',
                'tarikh_keahlian' => '2021-09-15',
                'created_by' => 1,
            ],
            [
                'nama' => 'Azizul bin Rahman',
                'no_ic' => '870318-18-9012',
                'telefon' => '011-0123456',
                'email' => 'azizul.rahman@email.com',
                'alamat' => 'No. 1113, Jalan Besar, Taman Indah, 96000 Sibu, Sarawak',
                'status' => 'Tidak Aktif',
                'tarikh_keahlian' => '2020-11-20',
                'created_by' => 1,
            ],
            [
                'nama' => 'Siti Nurhaliza binti Omar',
                'no_ic' => '920914-19-3456',
                'telefon' => '012-1234567',
                'email' => 'nurhaliza.omar@email.com',
                'alamat' => 'No. 1114, Jalan Baru, Taman Maju, 96000 Sibu, Sarawak',
                'status' => 'Aktif',
                'tarikh_keahlian' => '2023-02-28',
                'created_by' => 1,
            ],
            [
                'nama' => 'Khairuddin bin Hassan',
                'no_ic' => '881203-20-7890',
                'telefon' => '013-2345678',
                'email' => 'khairuddin.hassan@email.com',
                'alamat' => 'No. 1115, Jalan Lama, Taman Harmoni, 96000 Sibu, Sarawak',
                'status' => 'Aktif',
                'tarikh_keahlian' => '2021-05-12',
                'created_by' => 1,
            ],
            [
                'nama' => 'Rohani binti Yusuf',
                'no_ic' => '910428-21-1234',
                'telefon' => '014-3456789',
                'email' => 'rohani.yusuf@email.com',
                'alamat' => 'No. 1116, Jalan Ceria, Taman Bahagia, 96000 Sibu, Sarawak',
                'status' => 'Aktif',
                'tarikh_keahlian' => '2022-07-25',
                'created_by' => 1,
            ],
            [
                'nama' => 'Ahmad Fadzil bin Ibrahim',
                'no_ic' => '890715-22-5678',
                'telefon' => '015-4567890',
                'email' => 'fadzil.ibrahim@email.com',
                'alamat' => 'No. 1117, Jalan Damai, Taman Sejahtera, 96000 Sibu, Sarawak',
                'status' => 'Tidak Aktif',
                'tarikh_keahlian' => '2020-03-08',
                'created_by' => 1,
            ],
            [
                'nama' => 'Norazlina binti Mohd',
                'no_ic' => '930126-23-9012',
                'telefon' => '016-5678901',
                'email' => 'azlina.mohd@email.com',
                'alamat' => 'No. 1118, Jalan Makmur, Taman Jaya, 96000 Sibu, Sarawak',
                'status' => 'Aktif',
                'tarikh_keahlian' => '2023-06-14',
                'created_by' => 1,
            ],
            [
                'nama' => 'Zulkarnain bin Sulaiman',
                'no_ic' => '880909-24-3456',
                'telefon' => '017-6789012',
                'email' => 'zulkarnain.sulaiman@email.com',
                'alamat' => 'No. 1119, Jalan Maju, Taman Berjaya, 96000 Sibu, Sarawak',
                'status' => 'Aktif',
                'tarikh_keahlian' => '2021-12-03',
                'created_by' => 1,
            ],
            [
                'nama' => 'Siti Aisyah binti Rosli',
                'no_ic' => '920517-25-7890',
                'telefon' => '018-7890123',
                'email' => 'aisyah.rosli@email.com',
                'alamat' => 'No. 1120, Jalan Sukses, Taman Makmur, 96000 Sibu, Sarawak',
                'status' => 'Aktif',
                'tarikh_keahlian' => '2022-10-18',
                'created_by' => 1,
            ],
            [
                'nama' => 'Mohd Hafiz bin Kamal',
                'no_ic' => '891230-26-1234',
                'telefon' => '019-8901234',
                'email' => 'hafiz.kamal@email.com',
                'alamat' => 'No. 1121, Jalan Cemerlang, Taman Gemilang, 96000 Sibu, Sarawak',
                'status' => 'Aktif',
                'tarikh_keahlian' => '2020-08-22',
                'created_by' => 1,
            ],
            [
                'nama' => 'Nurul Huda binti Zainal',
                'no_ic' => '910823-27-5678',
                'telefon' => '011-9012345',
                'email' => 'huda.zainal@email.com',
                'alamat' => 'No. 1122, Jalan Berkat, Taman Rahmat, 96000 Sibu, Sarawak',
                'status' => 'Tidak Aktif',
                'tarikh_keahlian' => '2021-11-30',
                'created_by' => 1,
            ],
            [
                'nama' => 'Ahmad Irfan bin Hashim',
                'no_ic' => '930415-28-9012',
                'telefon' => '012-0123456',
                'email' => 'irfan.hashim@email.com',
                'alamat' => 'No. 1123, Jalan Mulia, Taman Indah, 96000 Sibu, Sarawak',
                'status' => 'Aktif',
                'tarikh_keahlian' => '2023-04-05',
                'created_by' => 1,
            ],
            [
                'nama' => 'Norhidayah binti Omar',
                'no_ic' => '890628-29-3456',
                'telefon' => '013-1234567',
                'email' => 'hidayah.omar@email.com',
                'alamat' => 'No. 1124, Jalan Utama, Taman Sentosa, 96000 Sibu, Sarawak',
                'status' => 'Aktif',
                'tarikh_keahlian' => '2022-01-12',
                'created_by' => 1,
            ],
            [
                'nama' => 'Mohd Azlan bin Yusof',
                'no_ic' => '920311-30-7890',
                'telefon' => '014-2345678',
                'email' => 'azlan.yusof@email.com',
                'alamat' => 'No. 1125, Jalan Besar, Taman Damai, 96000 Sibu, Sarawak',
                'status' => 'Aktif',
                'tarikh_keahlian' => '2021-07-08',
                'created_by' => 1,
            ],
            [
                'nama' => 'Siti Nurul Ain binti Ismail',
                'no_ic' => '910716-31-1234',
                'telefon' => '015-3456789',
                'email' => 'nurul.ain@email.com',
                'alamat' => 'No. 1126, Jalan Merdeka, Taman Jaya, 96000 Sibu, Sarawak',
                'status' => 'Aktif',
                'tarikh_keahlian' => '2023-09-20',
                'created_by' => 1,
            ],
            [
                'nama' => 'Khairul Anuar bin Ahmad',
                'no_ic' => '881019-32-5678',
                'telefon' => '016-4567890',
                'email' => 'khairul.anuar@email.com',
                'alamat' => 'No. 1127, Jalan Utama, Taman Sentosa, 96000 Sibu, Sarawak',
                'status' => 'Tidak Aktif',
                'tarikh_keahlian' => '2020-12-15',
                'created_by' => 1,
            ],
            [
                'nama' => 'Noraziah binti Rahman',
                'no_ic' => '930122-33-9012',
                'telefon' => '017-5678901',
                'email' => 'aziah.rahman@email.com',
                'alamat' => 'No. 1128, Jalan Besar, Taman Indah, 96000 Sibu, Sarawak',
                'status' => 'Aktif',
                'tarikh_keahlian' => '2022-05-28',
                'created_by' => 1,
            ],
            [
                'nama' => 'Mohd Firdaus bin Omar',
                'no_ic' => '900425-34-3456',
                'telefon' => '018-6789012',
                'email' => 'firdaus.omar@email.com',
                'alamat' => 'No. 1129, Jalan Baru, Taman Maju, 96000 Sibu, Sarawak',
                'status' => 'Aktif',
                'tarikh_keahlian' => '2021-03-17',
                'created_by' => 1,
            ],
            [
                'nama' => 'Siti Noraini binti Hassan',
                'no_ic' => '920818-35-7890',
                'telefon' => '019-7890123',
                'email' => 'noraini.hassan@email.com',
                'alamat' => 'No. 1130, Jalan Lama, Taman Harmoni, 96000 Sibu, Sarawak',
                'status' => 'Aktif',
                'tarikh_keahlian' => '2023-11-10',
                'created_by' => 1,
            ],
        ];

        foreach ($sampleData as $data) {
            Ppjub::create($data);
        }
    }
}
